# -----------------------------------------------------------------------------
# DiT modelconfig
# -----------------------------------------------------------------------------
dit:
 name: "LDMol" # DiT model DiT_models 
 
 latent_size: 127 # Autoencoder latent length
 in_channels: 64 # latent 
 cross_attn_dim: 768 # cross attention dimension
 condition_dim: 2048 # conditionembeddingdimension

# -----------------------------------------------------------------------------
# SMILES Encoder config
# -----------------------------------------------------------------------------
smiles_encoder:
 name: "autoencoder" 
 ckpt: "${CHECKPOINT_DIR:-/path/to/checkpoints}/diffusion_pretrained/official/checkpoint_autoencoder.ckpt"
 

# -----------------------------------------------------------------------------
# Text Encoder config
# -----------------------------------------------------------------------------
text_encoder:
 name: "qwen3_8b" # Text Encoder typesupports qwen3_8b
 ckpt: "${CHECKPOINT_DIR:-/path/to/checkpoints}/qwen3_8b_cpt_sft/epoch2/LLM_nofreeze/checkpoint-4200/llm" # Text Encoder trainingweightpath
 hidden_dim: 4096 
 description_length: 256 # LLM hiddenlayerdimensionQwen3_8B: 4096

# -----------------------------------------------------------------------------
# training
# -----------------------------------------------------------------------------
train:
 results_dir: "./eval_results/results/ldmol-qwen_cpt_sft" # outputdirectory

 data_paths: [ 
 "${SCICORE_ROOT:-/path/to/scicore-mol}/eval_results/data/ldmol/drug_optim/processed/train_mol_edit.txt"
 ] # trainingdatapathsupports .txt .csv

 ckpt: "${CHECKPOINT_DIR:-/path/to/checkpoints}/diffusion_pretrained/ours/ldmol/ldmol_chatmol-qwen3_8b.pt"
 
 epochs: 300 # training
 global_batch_size: 96 # global batch size
 learning_rate: 1.0e-4 # learning rate
 unconditional_prob: 0.05 # conditiontrainingfor CFG
 ema_decay: 0.9999 # EMA 
 log_every: 100 # log N 
 ckpt_every: 5000 # save checkpoint N 

# -----------------------------------------------------------------------------
# inference
# -----------------------------------------------------------------------------
infer: 
 results_dir: TODO
 data_paths: [
 "${SCICORE_ROOT:-/path/to/scicore-mol}/eval_results/data/ldmol/drug_optim/processed/test_t2m.txt"
 ]
 ckpt: "${SCICORE_ROOT:-/path/to/scicore-mol}/eval_results/results/ldmol-qwen_cpt_sft-drug_optim/000-LDMol/checkpoints/0007000.pt" # not null if test



# -----------------------------------------------------------------------------
#
# -----------------------------------------------------------------------------
global_seed: 0 # random
num_workers: 8 # DataLoader workers count
tf32: true # whether TF32 
