# Layer2 configfile
# LDMol config

# modelconfig
# NOTEconfigmust checkpoint configconsistent
# checkpoint use hidden_dim=768 (medium config)
mol_emb_dim: 256
hidden_dim: 768 # checkpoint readshould 768
n_layers: 8 # checkpoint readshould 8
n_heads: 12 # checkpoint readshould 12
dropout: 0.1
num_roles: 11
num_token_types: 2
tau: 0.07
learnable_tau: false
symmetric_ince: false

# modelweightpathconfigfilepath
checkpoint_path: "${SCICORE_ROOT:-/path/to/scicore-mol}/Layer2/ckpt/0115/layer2_pretrain.pt" # Layer2 pretrained checkpoint

# GVP 
gvp_root: "${DATA_DIR:-/path/to/data}/MSMLM" # GVP directorydefault
gvp_ckpt_path: "${CHECKPOINT_DIR:-/path/to/checkpoints}/gvp_weights_best.pt" # GVP checkpoint pathdefault

# inferenceparameter
yield_mode: "both" # "reg_only", "bin_only", "soft_bin_only", "both"
